# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88332eee56f990c1adcfebac83bf1640d07a78037a33e672f9271c4b41bbdec7380eff4fd9cd188c0dfea191e26c521077b659c26f720df1ebd5a12e59738a08

test:
  secret_key_base: 8662cd49f6eab7c3bb0e86e5a98d39d77ac87538fb82a41c3f18721e183b7ba5df06ca7645570cd530b2def09b09a12ed3fd0c18d20d833f81901cdbf6f362c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
